### ISSUE TITLE
Update to Socket.IO 0.8.6 

### ISSUE THREAD

**Issue by ghost** [jeromeetienne/EasyWebsocket#4]
Any chance to update EasyWebsocket to the new release of Socket.IO 0.8.6?

**Comment by jeromeetienne** [comment]
any advantage on current version ?

**Comment by ghost** [comment]
Summary:
Major speed optimizations (parser 50%-200% faster)
Added benchmarks to build process
HTML5 WebWorker support on the client
More client caching options (/socket.io/socket.io.vx.x.x.js will send far-future Expires)
Upcoming IE10 WebSocket support
Server tests improvements
Client acceptance tests improvements
Lots of bug-fixes and minor enhancements.

Server

# 0.8.6 / 2011-10-27 
- Added JSON decoding on jsonp-polling transport.
- Fixed README example.
- Major speed optimizations [3rd-Eden] [einaros] [visionmedia]
- Added decode/encode benchmarks [visionmedia]
- Added support for black-listing client sent events.
- Fixed logging options, closes #540 [3rd-Eden]
- Added vary header for gzip [3rd-Eden]
- Properly cleaned up async websocket / flashsocket tests, after patching node-websocket-client
- Patched to properly shut down when a finishClose call is made during connection establishment
- Added support for socket.io version on url and far-future Expires [3rd-Eden] [getify]
- Began IE10 compatibility [einaros] [tbranyen]
- Misc WebSocket fixes [einaros]
- Added UTF8 to respone headers for htmlfile [3rd-Eden]

Client

# 0.8.6 / 2011-10-27 
- Added WebWorker support.
- Fixed swfobject and web_socket.js to not assume window.
- Fixed CORS detection for webworker.
- Fix `defer` for webkit in a webworker.
- Fixed io.util.request to not rely on window.
- FIxed; use global instead of window and dont rely on document.
- Fixed; JSON-P handshake if CORS is not available.
- Made underlying Transport disconnection trigger immediate socket.io disconnect.
- Fixed warning when compressing with Google Closure Compiler.
- Fixed builder's uglify utf-8 support.
- Added workaround for loading indicator in FF jsonp-polling. [3rd-Eden]
- Fixed host discovery lookup. [holic]
- Fixed close timeout when disconnected/reconnecting. [jscharlach]
- Fixed jsonp-polling feature detection.
- Fixed jsonp-polling client POSTing of \n.
- Fixed test runner on IE6/7

Special thanks as always to the socket.io team, bug reporters & testers, and everyone who provided ideas!

## 

Guillermo Rauch
LearnBoost CTO
http://devthought.com

**Comment by jeromeetienne** [comment]
It seems significant. I dont have much time tho. Care enougth to make a pull
request ? they are always welcome :)

**Comment by ghost** [comment]
Sorry, can't help with that, just new to the Git and node.js world!
