### ISSUE TITLE
The connection was interrupted while the page was loading.

### ISSUE THREAD

**Issue by tdbe** [jeromeetienne/EasyWebsocket#6]
I've been using your fantastic library for a few months. Recently though, my connection started to fail after a few seconds (~23s), or when I send something. It started around this christmas, but I haven't had time to look into it until now.

Firefox, (firebug) reports:
"
The connection to ws://88.191.76.230:8950/socket.io/1/websocket/18883451342134888172 was interrupted while the page was loading.

...this,e;e||(e=window.MozWebSocket||window.WebSocket);this.websocket=new e(this.pr...   at: easyWe....min.js (line 43)
"
Chrome fails silently after the same amount of time.

This is the code I am using: this._connection = new EasyWebSocket("ws://students.info.uaic.ro/~tudor.berechet/index.xhtml");
So it is not "wss", as it was mentioned in this issue: https://github.com/jeromeetienne/EasyWebsocket/issues/5
Sometimes one or two broadcasts make it through, but usually it keeps failing with that error every time I try to send something.

Haven't had time to look at your un-minified code yet.

**Comment by jeromeetienne** [comment]
Sorry i
 Quite busy with three.js webgl these days. Is this failling when you run the server locally too?

**Comment by tdbe** [comment]
Yes, just ran it in Firefox off WampServer, localhost, and the same error. What exactly does the error mean? Why would the server be interrupting the connection ? (if that's the case)

Also, I never really understood what are you doing with whatever url I pass to the new EasyWebSocket("ws://foo.com/bar");. What's it for? (since you seem to be using "ws://88.191.76.230:8950/socket.io")

**Comment by tdbe** [comment]
Jerome, I don't know what you've done, but as of right now, everything works as it should. No more disconnections!

And it's not even my birthday! Thank you for being awesome.
