### ISSUE TITLE
please help me with client refresh through websocekt

### ISSUE THREAD

**Issue by Pryme8** [jeromeetienne/EasyWebsocket#7]
Ok I have a page that is running a web socket with a timer, that on a 15 second interval it sends through the socket the value "refresh",  on the client pages I have javascript set up I believe to listen for a send event through the web socket and if the information sent is "refresh" for the clients page to refresh...

the problem is once it has been sent once It holds the event data of refresh and just keeps trying to refresh the page as fast as it can...  Ive tried a bunch of different options and at first I thought the page would stop refreshing after some time because the socket does not work, but I traced the socekts send with and alert box as apposed to "run this function" and it seems to work...

server Page:

<script src="easyWebSocket.min.js"></script>

<script type="text/javascript">
var socket = new EasyWebSocket("ws://localhost/test");
var t;
var timer_is_on=0;
var interval

function startServer(){
interval = setInterval("timedCount()", 15000);  
}
function stopServer(){
clearInterval(interval);    
}

 function timeUpdate(){
   document.getElementById("servertime").contentWindow.location.reload();
 }

function timedCount()
{
timeUpdate();
socket.send("refresh");
}

function doTimer()
{
if (!timer_is_on)
  {
  timer_is_on=1;
  timedCount();
  }
}
</script>

</head>

<body>

<form>
<input type="button" value="Start Server!" onClick="startServer()">
<input type="button" value="STOP Server!" onClick="stopServer()">
<div><iframe id=servertime src=timeManager.php></iframe></div>

</form>

</body>

CLIENTS PAGE:

<script src="easyWebSocket.min.js"></script>

<script type="text/javascript">
var socket = new EasyWebSocket("ws://localhost/test");
     
        
        
        socket.onmessage = function(event){
        if (event.data=="refresh"){
        window.location.replace("GUI.php");
        }
        }
</script>

**Comment by jeromeetienne** [comment]
hi

from memory, you had connection issue. When you run your server, you have to setup the specific address like here
https://github.com/jeromeetienne/EasyWebsocket/blob/master/example/devel-node.html#L16

**Comment by Pryme8** [comment]
<script src="easyWebSocket.min.js"></script>

<script type="text/javascript">

EasyWebSocket.serverUrl = "http://127.0.0.0.1:9235"; <!-- I added this but it does nothing... I still get the connection dropouts!

var socket = new EasyWebSocket("ws://localhost/test");
var t;
var timer_is_on=0;
var interval

function startServer(){
interval = setInterval("timedCount()", 15000);  
}
function stopServer(){
clearInterval(interval);  
}

 function timeUpdate(){
 document.getElementById("servertime").contentWindow.location.reload();
 }

function timedCount()
{
timeUpdate();
socket.send("refresh");
}

function doTimer()
{
if (!timer_is_on)
  {
  timer_is_on=1;
  timedCount();
  }
}

//****\* ERROR
Timestamp: 3/16/2012 11:27:27 PM
Error: The connection to ws://88.191.76.230:8950/socket.io/1/websocket/15873904321378078191 was interrupted while the page was loading.
Source File: http://localhost/schoolphp/mapmove/easyWebSocket.min.js
Line: 43

**Comment by jeromeetienne** [comment]
http://localhost/schoolphp/mapmove/easyWebSocket.min.js <- try with the unminified version

**Comment by Pryme8** [comment]
<script src="easyWebSocket.min.js"></script>


is the one im using now, do you mean for me to use the node one?

I tried following your examples to get the node and socket.io one working but for some reason I can never even establish a connection or send anything with that one... must just be what I doing wrong...

Is there some sort of report I can export to show whats going on?

**Comment by Pryme8** [comment]
do i need to close the socket each time before i refresh the page?

**Comment by jeromeetienne** [comment]
Your case is the same as the one when i dev node locally. Run the node dev
example

On Saturday, March 17, 2012, Pryme8 <
reply@reply.github.com>
wrote:

**Comment by Pryme8** [comment]
ill give it a shot today, if it works once I get the websocket running ill put you on the games credits for helping with the server.

**Comment by Pryme8** [comment]
can you link me to the dev node? or how to implement it?
